name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
        name: Job Notification
      - uses: actions/checkout@master
        name: Checkout Repository
      - name: Testing
        run: make test
